### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by yuri050** [yuri050/protospace--user_id#1]
自身のProtoSpaceのURL（本番環境）

**Comment by yusuketono** [comment]
@yuri050  さん、ご提出ありがとうございます‼︎
ProtoSpaceのURLのご記載がないようですので、お手数ですが再度ご提出をお願いします！

**Comment by yuri050** [comment]
@yusuketono san
すみません！下記になります！
https://protospace-37329.herokuapp.com/

**Comment by yuri050** [comment]
>

**Comment by yusuketono** [comment]
@yuri050 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できること**
削除ボタンをクリックするとエラー画面に遷移してしまうので、削除できるように修正しましょう。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yuri050** [comment]
> 
ご確認ありがとうございます！
私の方だと自身が投稿したものを詳細ページから削除できるのですが
どこの箇所の削除になりますでしょうか？
お忙しいところ申し訳ございませんが、詳しくご教示いただけますと助かります！mm

**Comment by yusuketono** [comment]
@yuri050 さん、ご返信ありがとうございます!!
下記の動画のように、ログインユーザーが投稿したプロトタイプにおいて、削除ボタンをクリックするとエラー画面へ遷移してしまいます。
https://user-images.githubusercontent.com/51428519/165652898-e868f99e-3d7c-4989-8ccf-2acc9d253c45.mov

本番環境へのデプロイが上手く実行できていない可能性があるので、お手数ですが再度ご確認をお願いいたします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yuri050** [comment]
＠yusuketono　さん
ご確認ありがとうございます！
herokuのログの情報を確認したのですが、エラーらしきものは見つからず；

最新の箇所に
Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms | Allocations: 400)
とあったため、色々調べてみたのですがはっきりと原因がわからなかったため
どこかソースが誤っているのかと再確認し、数カ所訂正→コミットプッシュしたので
再度ご確認いただけますでしょうか？

エラー画面がこちらで確認が取れないため
どこの箇所が原因として該当するかも
ご教示いただくことは可能でしょうか？

お忙しいところ申し訳ありませんが
宜しくお願いいたします！

**Comment by yusuketono** [comment]
@yuri050 さん、ご返信ありがとうございます!!

> エラー画面がこちらで確認が取れないため
> どこの箇所が原因として該当するかも
> ご教示いただくことは可能でしょうか？

エラーに関するご説明が不足しており大変申し訳ございません。
「ログインユーザーが投稿したプロトタイプにおいて、削除ボタンをクリックするとエラー画面に遷移する」という内容のエラーが発生しており、修正を依頼させていただきました。
![スクリーンショット 2022-05-02 10 14 48](https://user-images.githubusercontent.com/51428519/166173459-3bc5af60-df52-4fab-97b0-d559b0e8a4bf.png)
![スクリーンショット 2022-05-02 10 20 51](https://user-images.githubusercontent.com/51428519/166173670-2e39dec4-dce1-4d8c-82df-37c33f033878.png)

再度ご提出いただいた内容を確認したところ、新規に投稿したプロトタイプについては削除できることが確認できましたので、
**LGTM**とさせていただきます。　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

**Comment by yuri050** [comment]
ありがとうございます！！
助かりました！
